name: Publish Package to Github

on:
  push:
    branches: [main]

jobs:
  publish-to-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@mosefatullah'
      - run: npm ci
      - run: echo registry=https://npm.pkg.github.com/mosefatullah >> .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_GITHUB}} 